# Make sure to check the documentation at https://goreleaser.com
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/zek/main.go
archives:
  - id: zek
    name_template: >-
     {{- .ProjectName }}_
     {{- title .Os }}_
     {{- if eq .Arch "amd64" }}x86_64
     {{- else if eq .Arch "386" }}i386
     {{- else }}{{ .Arch }}{{ end }}
     {{- if .Arm }}v{{ .Arm }}{{ end -}}
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
